[build.environment]
  YARN_VERSION = "1.19.1"
  NODE_VERSION = "10.16.2"
  NODE_ENV = "production"

[[redirects]]
  from = "/graphql"
  to = "https://nuffread.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

