[build.environment]
  YARN_VERSION = "1.21.1"
  NODE_VERSION = "12.16.1"

[[redirects]]
  from = "/graphql"
  to = "https://nuffread.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

