[build]
  # ignore exclusive changes in api/
  # based on https://stackoverflow.com/questions/4380945/exclude-a-directory-from-git-diff
  ignore = "git diff --quiet HEAD^ HEAD -- . ':!api/'"

[build.environment]
  YARN_VERSION = "1.21.1"
  NODE_VERSION = "10.16.2"

[[redirects]]
  from = "/graphql"
  to = "https://nuffread.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

