[build]
  environment = { YARN_VERSION = "1.17.3" }

[[redirects]]
  from = "/graphql"
  to = "https://nuffread.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

