scalar Date

enum SystemUserType {
  ADMIN
  USER
}

input PaginationInput {
  limit: Int
  offset: Int
}
type PaginatedListings {
  items: [Listing!]!
  totalCount: Int!
}

type Query {
  search(
    query: String
    maxPrice: Int
    minPrice: Int
    paginate: PaginationInput
  ): PaginatedListings!
  top(paginate: PaginationInput): PaginatedListings!

  me: SystemUser

  listing(id: ID!): Listing
  book(id: ID!): Book

  invites: [Invite!]!
  schools: [School!]!
  sessions: [Session!]!

  searchGoogle(query: String!): [GoogleBook!]
  googleBook(id: ID!): GoogleBook!
}

type Mutation {
  createUser(user: UserInput!): User!
  toggleUserTrackable: User!

  requestInvite(email: String!, name: String!): Boolean!
  sendInvite(email: String!): Invite!
  resendConfirmEmail(email: String!): Boolean!

  register(email: String!, password: String!): User!
  login(email: String!, password: String!, type: SystemUserType!): SystemUser!
  logout: Boolean!
  confirm(code: String!): Boolean!
  requestResetPassword(email: String!): Boolean!
  resetPassword(token: String!, password: String!): Boolean!

  createListing(listing: ListingInput!): Listing!
  deleteListing(id: ID!): Boolean

  setSchoolName(id: ID!, name: String!): School!

  saveListing(listingId: ID!, saved: Boolean!): Listing!
  sellListing(listingId: ID!, price: Int!): Listing!
  setPrice(listingId: ID!, price: Int!): Listing!
}

type Invite {
  email: String!
  name: String!
  user: User
  invitedAt: Date
}

type User {
  id: ID!

  email: String!
  name: String
  photo: String
  isTrackable: Boolean!

  listings: [Listing!]!
  recent: [Listing!]!
  saved(paginate: PaginationInput): PaginatedListings!

  invite: Invite!

  confirmedAt: Date
  schoolName: String @deprecated(reason: "use school.name instead")
  school: School!
}

input UserInput {
  name: String!
}

type Admin {
  id: ID!

  email: String!
}

union SystemUser = Admin | User

type Listing {
  id: ID!
  createdAt: Date!
  price: Int!
  description: String!

  book: Book!
  user: User
  # references user.school without revealing much user information
  school: School!

  saved: Boolean
  soldAt: Date
  soldPrice: Int
}

input ListingInput {
  googleId: String!
  price: Int!
  description: String!
  coverIndex: Int # optional for backwards compat reasons
}

type Book {
  id: String!
  etag: String
  googleId: String
  authors: [String!]!
  isbn: [String!]!
  publishedAt: Date
  title: String!
  subTitle: String
  thumbnail: String

  listings(paginate: PaginationInput): PaginatedListings!
}

# book but without id
type GoogleBook {
  etag: String
  googleId: String!
  authors: [String!]!
  isbn: [String!]!
  publishedAt: Date
  title: String!
  subTitle: String
  thumbnail: String
  possibleCovers: [String!]!
}

type School {
  id: ID!
  name: String!
  # only accessible to administrators
  domain: String!
}

type Session {
  id: ID!
  expiresAt: Date!

  user: SystemUser!
}
