scalar Date

enum UserType {
  ADMIN
  SELLER
}

type Query {
  search(query: String, maxPrice: Int, minPrice: Int): [Listing!]!

  me: User!

  listing(id: ID!): Listing
}

type Mutation {
  createSeller(seller: SellerInput!): Seller!
  deleteSeller(id: ID!): Boolean!

  createSchool(school: SchoolInput!): School!
  deleteSchool(id: ID!): Boolean!

  register(email: String!, password: String!): Boolean!
  login(email: String!, password: String!, type: UserType!): Boolean!
  logout: Boolean!
}

type Seller {
  id: ID!

  email: String!
  name: String
  photo: String
}

input SellerInput {
  schoolId: ID!
  name: String!
}

type School {
  id: ID!

  name: String!
}

input SchoolInput {
  name: String!
}

type Admin {
  id: ID!

  email: String!
}

union User = Admin | Seller

type Listing {
  id: ID!

  isbn: [String!]!
  thumbnail: String
  title: String!
  subTitle: String
  authors: [String!]!
  publishedAt: Date!
  price: Int!

  schoolId: String!
  school: School!
  sellerId: String!
  seller: Seller!
}
