scalar Date

type Query {
  currentUser: Seller

  search(query: String, maxPrice: Int, minPrice: Int): [Listing!]!
}

type Mutation {
  createSeller(seller: SellerInput!): Seller!
  deleteSeller(id: ID!): Boolean!

  createSchool(school: SchoolInput!): School!
  deleteSchool(id: ID!): Boolean!
}

type Seller {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  name: String!
  email: String
  photo: String!
}

input SellerInput {
  schoolId: ID!
  name: String!
}

type School {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  name: String!
}

input SchoolInput {
  name: String!
}

type Admin {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  email: String!
}

union User = Admin | Seller

type Listing {
  id: ID!
  createdAt: Date!
  updatedAt: Date!

  isbn: [String!]!
  thumbnail: String
  title: String!
  subTitle: String
  authors: [String!]!
  publishedAt: Date!
  publisher: String
  price: Int!

  school: School!
  schoolId: String!
}
