scalar Date

enum SystemUserType {
  ADMIN
  USER
}

type Query {
  search(query: String, maxPrice: Int, minPrice: Int): [Listing!]!
  top: [Listing!]!

  me: SystemUser

  listing(id: ID!): Listing

  invites: [Invite!]!

  searchGoogle(query: String!): [GoogleBook!]
  googleBook(id: ID!): GoogleBook!
}

type Mutation {
  createUser(user: UserInput!): User!
  deleteUser(id: ID!): Boolean!

  requestInvite(email: String!, name: String!): Boolean!
  sendInvite(email: String!): Invite!

  register(email: String!, password: String!): User!
  login(email: String!, password: String!, type: SystemUserType!): SystemUser!
  logout: Boolean!
  confirm(code: String!): Boolean!
  # resendEmail(code: String!): Boolean!
  requestResetPassword(email: String!): Boolean!
  resetPassword(token: String!, password: String!): Boolean!

  createListing(listing: ListingInput!): Listing!
  deleteListing(id: ID!): Boolean
}

type Invite {
  email: String!
  name: String!
  user: User
  invitedAt: Date
}

type User {
  id: ID!

  email: String!
  name: String!
  photo: String

  listings: [Listing!]!
  invite: Invite!

  confirmedAt: Date
  schoolName: String
}

input UserInput {
  name: String!
}

type Admin {
  id: ID!

  email: String!
}

union SystemUser = Admin | User

type Listing {
  id: ID!
  createdAt: Date!
  price: Int!
  description: String!

  bookId: String!
  book: Book!
  userId: String!
  user: User!
}

input ListingInput {
  googleId: String!
  price: Int!
  description: String!
}

type Book {
  id: String!
  etag: String
  googleId: String
  authors: [String!]!
  isbn: [String!]!
  publishedAt: Date
  title: String!
  subTitle: String
  thumbnail: String
}

# book but without id
type GoogleBook {
  etag: String
  googleId: String!
  authors: [String!]!
  isbn: [String!]!
  publishedAt: Date
  title: String!
  subTitle: String
  thumbnail: String
}
